### ISSUE TITLE
Still leaks public IP

### ISSUE THREAD

**Issue by drmidnight** [CODYQX4/WebRTC-Multiple-Routes#1]
This helps in blocking the internal network address, but it will still leak your public IP.

**Comment by CODYQX4** [comment]
With a VPN, the VPN public IP leaks for me. Without a VPN, your ISP public IP is revealed.

The whole issue with the IP leak is that anyone can get your real IP, VPN or not, and a VPN user who wishes to stay anonymous must not leak their real IP.

Any site/web connection can get your public IP, WebRTC or not. Hence all of those forum signatures that show your IP and User Agent.

Firefox can be configured to completely disable WebRTC so that the WebRTC section shows nothing, but above, there will be your public IP, either ISP, or VPN if using one.

**Comment by drmidnight** [comment]
I completely understand the problem. I was simply stating your extension for toggling the chrome option doesn't stop WebRTC from getting your ISP public IP.

Of course I'm using a VPN and using this in conjunction does nothing about hiding your ISP's public IP. It still leaks. Disabling this option will leak your internal IP.
